# Generated by Django 2.2.22 on 2021-05-14 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_auto_20210514_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf',
            name='valf_govde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_govde'),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_kurlenme_baslangic_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_kurlenme_bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_kurlenme_parti_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_kurlenme_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='govde_kurlenme_personel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='govde_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='govde_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
