# Generated by Django 2.2.22 on 2021-05-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210514_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='valf_test',
            name='aciklama',
            field=models.CharField(blank=True, max_length=1000000000, null=True),
        ),
        migrations.AddField(
            model_name='valf_test',
            name='pdf_ismi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
