# Generated by Django 2.2.22 on 2021-05-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210520_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_test',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='valf_test',
            name='pdf_ismi',
        ),
    ]
