# Generated by Django 2.2.22 on 2021-05-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210522_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF_Rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istasyon', models.PositiveIntegerField(max_length=100)),
                ('valf_Seri_no', models.PositiveIntegerField(null=True)),
                ('pdf_ismi', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True, max_length=10000000000, null=True)),
            ],
        ),
    ]
