# Generated by Django 2.2.22 on 2021-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_pdf_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_rapor',
            name='istasyon',
            field=models.PositiveIntegerField(),
        ),
    ]
