# Generated by Django 2.2.22 on 2021-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210522_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf_rapor',
            old_name='valf_Seri_no',
            new_name='valf_seri_no',
        ),
        migrations.AddField(
            model_name='pdf_rapor',
            name='pdf',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
