# Generated by Django 2.2.22 on 2021-05-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210522_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf_rapor',
            name='pdf',
        ),
    ]
