# Generated by Django 2.2.22 on 2021-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_pdf_rapor_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_rapor',
            name='istasyon',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf_rapor',
            name='valf_seri_no',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
