# Generated by Django 2.2.22 on 2021-05-26 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0017_auto_20210523_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valf_fm200',
            old_name='rekorlu_agirlik',
            new_name='dolu_agirlik',
        ),
        migrations.RenameField(
            model_name='valf_fm200',
            old_name='kurlenme_bitis',
            new_name='fm200_kurlenme_baslangic_tarihi',
        ),
        migrations.RemoveField(
            model_name='valf_final_montaj',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='valf_final_montaj',
            name='valf',
        ),
        migrations.RemoveField(
            model_name='valf_fm200',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='valf_fm200',
            name='valf',
        ),
        migrations.RemoveField(
            model_name='valf_havuz',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='valf_havuz',
            name='valf',
        ),
        migrations.AddField(
            model_name='valf',
            name='fm200_azot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_fm200'),
        ),
        migrations.AddField(
            model_name='valf',
            name='havuz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_havuz'),
        ),
        migrations.AddField(
            model_name='valf',
            name='valf_final_montaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Valf_final_montaj'),
        ),
        migrations.AddField(
            model_name='valf_fm200',
            name='fm200_kurlenme_bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valf_fm200',
            name='fm200_kurlenme_personel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fm200_kurlenme_personel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valf_fm200',
            name='fm200_parti_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='valf_fm200',
            name='fm200_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fm200_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valf_havuz',
            name='havuz_kurlenme_baslangic_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valf_havuz',
            name='havuz_kurlenme_bitis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valf_havuz',
            name='havuz_kurlenme_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kurlenme_havuz_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valf_havuz',
            name='havuz_parti_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='valf_havuz',
            name='havuz_personel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='havuz_personel', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
