# Generated by Django 2.2.22 on 2021-05-26 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20210526_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_fm200',
            name='uygunluk',
        ),
        migrations.AddField(
            model_name='valf_govde',
            name='sebep',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='valf_havuz',
            name='havuz_kurlenme_personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kurlenmehavuz_personel', to=settings.AUTH_USER_MODEL),
        ),
    ]
