# Generated by Django 2.2.22 on 2021-05-29 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_valf_fm200_uygunluk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valf_govde',
            name='govde_kurlenme_parti_no',
        ),
    ]
