# Generated by Django 2.2.22 on 2021-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_valf_govde_govde_kurlenme_parti_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valf_govde',
            name='uygunluk',
            field=models.BooleanField(default=False),
        ),
    ]
